### ISSUE TITLE
Can't create tags or sets

### ISSUE THREAD

**Issue by MisterTimn** [EightBitz/Dungeondraft-Custom-Tags#1]
When clicking either add Tag or add Tag Set nothing happens. Need to add the tags through a text editor and then reload the asset folder in Custom-Tags software. Known issue or possible work-around for it?

Running on Windows 10 Pro 64 bit, latest updates.

**Comment by EightBitz** [comment]
You have to type something into the text box above the button. If you want to add a tag named "Rocks", you type the word "Rocks" in the text box above the "Add Tags" button, then click the button to add it to the list.
